apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: platemail-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: platemail
    spec:
      containers:
        - name: platemail
          image: gcr.io/diesel-rain-214205/platemail:release_five
          ports:
            - containerPort: 4000
          args: ["foreground"]
          env:
            - name: HOST
              value: "platemail.com"
            - name: PORT
              value: "4000"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secret_key_base
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db_password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db_name
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db_host
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command:
            [
              "/cloud_sql_proxy",
              "-instances=<diesel-rain-214205:us-central1:platemail-test>=tcp:5432",
              "-credential_file=/secrets/cloudsql/credentials.json",
            ]
          securityContext:
            runAsUser: 2
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
