apiVersion: v1
kind: Service
metadata:
  name: platemail-service
spec:
  ports:
    - port: 8080
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: platemail
  type: LoadBalancer
